package com.biosimilarity.lift.model.seleKt;

import com.biosimilarity.lift.model.seleKt.Absyn.*;

/** BNFC-Generated All Visitor */
public interface AllVisitor<R,A> extends
  com.biosimilarity.lift.model.seleKt.Absyn.RecordExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.Binding.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.RecordPtn.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.RecordVariable.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.CollectionExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ExtensionBodyExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.IntensionBodyExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.DomainDeclOrCond.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.DomainGen.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.DomainCond.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.DomainPtn.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.DomainExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.RecordSource.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.DomainCondition.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.Modality.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.RLambdaPCtxt.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ContinuePCtxt.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.FormalPCtxt.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ValuePCtxt.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.RLambdaLCtxt.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ContinueLCtxt.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.FormalLCtxt.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ValueLCtxt.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ValuePCtxtHole.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ValueLCtxtHole.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.LogicalGround.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.Comparison.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.RLambdaExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ContinueExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.FormalExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ValueExpr.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.ValueLiteral.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.StoreURL.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.WireURL.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.URL.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.URLPath.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.URLLocation.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.URLRsrcLocation.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.URLRelativePath.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.URLRoot.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.NetLocation.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.URLScheme.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.URLPathElement.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.DNSElement.Visitor<R,A>,
  com.biosimilarity.lift.model.seleKt.Absyn.Port.Visitor<R,A>
{}
