package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class AbstractionLCtxt extends RLambdaLCtxt {
  public final ListFormalLCtxt listformallctxt_;
  public final RLambdaLCtxt rlambdalctxt_;

  public AbstractionLCtxt(ListFormalLCtxt p1, RLambdaLCtxt p2) { listformallctxt_ = p1; rlambdalctxt_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RLambdaLCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.AbstractionLCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.AbstractionLCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.AbstractionLCtxt)o;
      return this.listformallctxt_.equals(x.listformallctxt_) && this.rlambdalctxt_.equals(x.rlambdalctxt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listformallctxt_.hashCode())+this.rlambdalctxt_.hashCode();
  }


}
