package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ApplicationLCtxt extends RLambdaLCtxt {
  public final RLambdaLCtxt rlambdalctxt_;
  public final ListRLambdaLCtxt listrlambdalctxt_;

  public ApplicationLCtxt(RLambdaLCtxt p1, ListRLambdaLCtxt p2) { rlambdalctxt_ = p1; listrlambdalctxt_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RLambdaLCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ApplicationLCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.ApplicationLCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.ApplicationLCtxt)o;
      return this.rlambdalctxt_.equals(x.rlambdalctxt_) && this.listrlambdalctxt_.equals(x.listrlambdalctxt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rlambdalctxt_.hashCode())+this.listrlambdalctxt_.hashCode();
  }


}
