package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ApplicationPCtxt extends RLambdaPCtxt {
  public final RLambdaPCtxt rlambdapctxt_;
  public final ListRLambdaPCtxt listrlambdapctxt_;

  public ApplicationPCtxt(RLambdaPCtxt p1, ListRLambdaPCtxt p2) { rlambdapctxt_ = p1; listrlambdapctxt_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RLambdaPCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ApplicationPCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.ApplicationPCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.ApplicationPCtxt)o;
      return this.rlambdapctxt_.equals(x.rlambdapctxt_) && this.listrlambdapctxt_.equals(x.listrlambdapctxt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rlambdapctxt_.hashCode())+this.listrlambdapctxt_.hashCode();
  }


}
