package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class AtomScheme extends URLScheme {
  public final String ident_;

  public AtomScheme(String p1) { ident_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.URLScheme.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.AtomScheme) {
      com.biosimilarity.lift.model.seleKt.Absyn.AtomScheme x = (com.biosimilarity.lift.model.seleKt.Absyn.AtomScheme)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
