package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class BehavioralDomainCondition extends DomainCondition {
  public final Modality modality_;
  public final DomainCondition domaincondition_;

  public BehavioralDomainCondition(Modality p1, DomainCondition p2) { modality_ = p1; domaincondition_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainCondition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.BehavioralDomainCondition) {
      com.biosimilarity.lift.model.seleKt.Absyn.BehavioralDomainCondition x = (com.biosimilarity.lift.model.seleKt.Absyn.BehavioralDomainCondition)o;
      return this.modality_.equals(x.modality_) && this.domaincondition_.equals(x.domaincondition_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.modality_.hashCode())+this.domaincondition_.hashCode();
  }


}
