package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class BindingExpr extends Binding {
  public final RecordPtn recordptn_1, recordptn_2;

  public BindingExpr(RecordPtn p1, RecordPtn p2) { recordptn_1 = p1; recordptn_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.Binding.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.BindingExpr) {
      com.biosimilarity.lift.model.seleKt.Absyn.BindingExpr x = (com.biosimilarity.lift.model.seleKt.Absyn.BindingExpr)o;
      return this.recordptn_1.equals(x.recordptn_1) && this.recordptn_2.equals(x.recordptn_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.recordptn_1.hashCode())+this.recordptn_2.hashCode();
  }


}
