package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class Collected extends RecordExpr {
  public final CollectionExpr collectionexpr_;

  public Collected(CollectionExpr p1) { collectionexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.Collected) {
      com.biosimilarity.lift.model.seleKt.Absyn.Collected x = (com.biosimilarity.lift.model.seleKt.Absyn.Collected)o;
      return this.collectionexpr_.equals(x.collectionexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.collectionexpr_.hashCode();
  }


}
