package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class Comparison implements java.io.Serializable {
  public abstract <R,A> R accept(Comparison.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Equality p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Less p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.More p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.LEq p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.GEq p, A arg);

  }

}
