package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ConditionIn extends DomainDeclOrCond {
  public final DomainCond domaincond_;

  public ConditionIn(DomainCond p1) { domaincond_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainDeclOrCond.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ConditionIn) {
      com.biosimilarity.lift.model.seleKt.Absyn.ConditionIn x = (com.biosimilarity.lift.model.seleKt.Absyn.ConditionIn)o;
      return this.domaincond_.equals(x.domaincond_);
    }
    return false;
  }

  public int hashCode() {
    return this.domaincond_.hashCode();
  }


}
