package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class Consed extends RecordExpr {
  public final DomainExpr domainexpr_;
  public final RecordExpr recordexpr_;

  public Consed(DomainExpr p1, RecordExpr p2) { domainexpr_ = p1; recordexpr_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.Consed) {
      com.biosimilarity.lift.model.seleKt.Absyn.Consed x = (com.biosimilarity.lift.model.seleKt.Absyn.Consed)o;
      return this.domainexpr_.equals(x.domainexpr_) && this.recordexpr_.equals(x.recordexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.domainexpr_.hashCode())+this.recordexpr_.hashCode();
  }


}
