package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class ContinuePCtxt implements java.io.Serializable {
  public abstract <R,A> R accept(ContinuePCtxt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.PushPromptPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.SubcontPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.PushSubContPCtxt p, A arg);

  }

}
