package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class ContinueLCtxt implements java.io.Serializable {
  public abstract <R,A> R accept(ContinueLCtxt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.PushPromptLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.SubconLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.PushSubContLCtxt p, A arg);

  }

}
