package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class Contexted extends RecordExpr {
  public final ListBinding listbinding_;
  public final RecordExpr recordexpr_;

  public Contexted(ListBinding p1, RecordExpr p2) { listbinding_ = p1; recordexpr_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.Contexted) {
      com.biosimilarity.lift.model.seleKt.Absyn.Contexted x = (com.biosimilarity.lift.model.seleKt.Absyn.Contexted)o;
      return this.listbinding_.equals(x.listbinding_) && this.recordexpr_.equals(x.recordexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listbinding_.hashCode())+this.recordexpr_.hashCode();
  }


}
