package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class DeclIn extends DomainDeclOrCond {
  public final DomainGen domaingen_;

  public DeclIn(DomainGen p1) { domaingen_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainDeclOrCond.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.DeclIn) {
      com.biosimilarity.lift.model.seleKt.Absyn.DeclIn x = (com.biosimilarity.lift.model.seleKt.Absyn.DeclIn)o;
      return this.domaingen_.equals(x.domaingen_);
    }
    return false;
  }

  public int hashCode() {
    return this.domaingen_.hashCode();
  }


}
