package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class DisjunctDomainCondition extends DomainCondition {
  public final DomainCondition domaincondition_1, domaincondition_2;

  public DisjunctDomainCondition(DomainCondition p1, DomainCondition p2) { domaincondition_1 = p1; domaincondition_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainCondition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.DisjunctDomainCondition) {
      com.biosimilarity.lift.model.seleKt.Absyn.DisjunctDomainCondition x = (com.biosimilarity.lift.model.seleKt.Absyn.DisjunctDomainCondition)o;
      return this.domaincondition_1.equals(x.domaincondition_1) && this.domaincondition_2.equals(x.domaincondition_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.domaincondition_1.hashCode())+this.domaincondition_2.hashCode();
  }


}
