package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class DomainDeclOrCond implements java.io.Serializable {
  public abstract <R,A> R accept(DomainDeclOrCond.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ConditionIn p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.DeclIn p, A arg);

  }

}
