package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class DomainCompExpr extends DomainCond {
  public final ValueExpr valueexpr_1, valueexpr_2;
  public final Comparison comparison_;

  public DomainCompExpr(ValueExpr p1, Comparison p2, ValueExpr p3) { valueexpr_1 = p1; comparison_ = p2; valueexpr_2 = p3; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainCond.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.DomainCompExpr) {
      com.biosimilarity.lift.model.seleKt.Absyn.DomainCompExpr x = (com.biosimilarity.lift.model.seleKt.Absyn.DomainCompExpr)o;
      return this.valueexpr_1.equals(x.valueexpr_1) && this.comparison_.equals(x.comparison_) && this.valueexpr_2.equals(x.valueexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.valueexpr_1.hashCode())+this.comparison_.hashCode())+this.valueexpr_2.hashCode();
  }


}
