package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class DomainPtnExpr extends DomainPtn {
  public final RLambdaPCtxt rlambdapctxt_;

  public DomainPtnExpr(RLambdaPCtxt p1) { rlambdapctxt_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainPtn.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.DomainPtnExpr) {
      com.biosimilarity.lift.model.seleKt.Absyn.DomainPtnExpr x = (com.biosimilarity.lift.model.seleKt.Absyn.DomainPtnExpr)o;
      return this.rlambdapctxt_.equals(x.rlambdapctxt_);
    }
    return false;
  }

  public int hashCode() {
    return this.rlambdapctxt_.hashCode();
  }


}
