package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class DomainCondition implements java.io.Serializable {
  public abstract <R,A> R accept(DomainCondition.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.DisjunctDomainCondition p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ConjunctDomainCondition p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.NegatedDomainCondition p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.StructuralDomainCondition p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.BehavioralDomainCondition p, A arg);

  }

}
