package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class DomainGenExpr extends DomainGen {
  public final DomainPtn domainptn_;
  public final RecordSource recordsource_;

  public DomainGenExpr(DomainPtn p1, RecordSource p2) { domainptn_ = p1; recordsource_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainGen.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.DomainGenExpr) {
      com.biosimilarity.lift.model.seleKt.Absyn.DomainGenExpr x = (com.biosimilarity.lift.model.seleKt.Absyn.DomainGenExpr)o;
      return this.domainptn_.equals(x.domainptn_) && this.recordsource_.equals(x.recordsource_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.domainptn_.hashCode())+this.recordsource_.hashCode();
  }


}
