package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class DomainSatExpr extends DomainCond {
  public final DomainPtn domainptn_;
  public final DomainCondition domaincondition_;

  public DomainSatExpr(DomainPtn p1, DomainCondition p2) { domainptn_ = p1; domaincondition_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainCond.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.DomainSatExpr) {
      com.biosimilarity.lift.model.seleKt.Absyn.DomainSatExpr x = (com.biosimilarity.lift.model.seleKt.Absyn.DomainSatExpr)o;
      return this.domainptn_.equals(x.domainptn_) && this.domaincondition_.equals(x.domaincondition_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.domainptn_.hashCode())+this.domaincondition_.hashCode();
  }


}
