package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class DomainCond implements java.io.Serializable {
  public abstract <R,A> R accept(DomainCond.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.DomainSatExpr p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.DomainCompExpr p, A arg);

  }

}
