package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ExtensionBody extends ExtensionBodyExpr {
  public final ListDomainExpr listdomainexpr_;

  public ExtensionBody(ListDomainExpr p1) { listdomainexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ExtensionBodyExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ExtensionBody) {
      com.biosimilarity.lift.model.seleKt.Absyn.ExtensionBody x = (com.biosimilarity.lift.model.seleKt.Absyn.ExtensionBody)o;
      return this.listdomainexpr_.equals(x.listdomainexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdomainexpr_.hashCode();
  }


}
