package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class Extension extends CollectionExpr {
  public final ExtensionBodyExpr extensionbodyexpr_;

  public Extension(ExtensionBodyExpr p1) { extensionbodyexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.CollectionExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.Extension) {
      com.biosimilarity.lift.model.seleKt.Absyn.Extension x = (com.biosimilarity.lift.model.seleKt.Absyn.Extension)o;
      return this.extensionbodyexpr_.equals(x.extensionbodyexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.extensionbodyexpr_.hashCode();
  }


}
