package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class GroundPCtxt extends RLambdaPCtxt {
  public final ValuePCtxt valuepctxt_;

  public GroundPCtxt(ValuePCtxt p1) { valuepctxt_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RLambdaPCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.GroundPCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.GroundPCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.GroundPCtxt)o;
      return this.valuepctxt_.equals(x.valuepctxt_);
    }
    return false;
  }

  public int hashCode() {
    return this.valuepctxt_.hashCode();
  }


}
