package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class Intension extends CollectionExpr {
  public final IntensionBodyExpr intensionbodyexpr_;

  public Intension(IntensionBodyExpr p1) { intensionbodyexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.CollectionExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.Intension) {
      com.biosimilarity.lift.model.seleKt.Absyn.Intension x = (com.biosimilarity.lift.model.seleKt.Absyn.Intension)o;
      return this.intensionbodyexpr_.equals(x.intensionbodyexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.intensionbodyexpr_.hashCode();
  }


}
