package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class IntensionBody extends IntensionBodyExpr {
  public final DomainPtn domainptn_;
  public final ListDomainDeclOrCond listdomaindeclorcond_;

  public IntensionBody(DomainPtn p1, ListDomainDeclOrCond p2) { domainptn_ = p1; listdomaindeclorcond_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.IntensionBodyExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.IntensionBody) {
      com.biosimilarity.lift.model.seleKt.Absyn.IntensionBody x = (com.biosimilarity.lift.model.seleKt.Absyn.IntensionBody)o;
      return this.domainptn_.equals(x.domainptn_) && this.listdomaindeclorcond_.equals(x.listdomaindeclorcond_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.domainptn_.hashCode())+this.listdomaindeclorcond_.hashCode();
  }


}
