package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class Joined extends RecordExpr {
  public final RecordExpr recordexpr_1, recordexpr_2;

  public Joined(RecordExpr p1, RecordExpr p2) { recordexpr_1 = p1; recordexpr_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.Joined) {
      com.biosimilarity.lift.model.seleKt.Absyn.Joined x = (com.biosimilarity.lift.model.seleKt.Absyn.Joined)o;
      return this.recordexpr_1.equals(x.recordexpr_1) && this.recordexpr_2.equals(x.recordexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.recordexpr_1.hashCode())+this.recordexpr_2.hashCode();
  }


}
