package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class KLCtxt extends RLambdaLCtxt {
  public final ContinueLCtxt continuelctxt_;

  public KLCtxt(ContinueLCtxt p1) { continuelctxt_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RLambdaLCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.KLCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.KLCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.KLCtxt)o;
      return this.continuelctxt_.equals(x.continuelctxt_);
    }
    return false;
  }

  public int hashCode() {
    return this.continuelctxt_.hashCode();
  }


}
