package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class KPCtxt extends RLambdaPCtxt {
  public final ContinuePCtxt continuepctxt_;

  public KPCtxt(ContinuePCtxt p1) { continuepctxt_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RLambdaPCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.KPCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.KPCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.KPCtxt)o;
      return this.continuepctxt_.equals(x.continuepctxt_);
    }
    return false;
  }

  public int hashCode() {
    return this.continuepctxt_.hashCode();
  }


}
