package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class LogicalGround implements java.io.Serializable {
  public abstract <R,A> R accept(LogicalGround.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Verity p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Absurdity p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Nullity p, A arg);

  }

}
