package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class MentionPCtxt extends RLambdaPCtxt {
  public final FormalPCtxt formalpctxt_;

  public MentionPCtxt(FormalPCtxt p1) { formalpctxt_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RLambdaPCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.MentionPCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.MentionPCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.MentionPCtxt)o;
      return this.formalpctxt_.equals(x.formalpctxt_);
    }
    return false;
  }

  public int hashCode() {
    return this.formalpctxt_.hashCode();
  }


}
