package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class OnBoardSource extends RecordSource {
  public final RecordExpr recordexpr_;

  public OnBoardSource(RecordExpr p1) { recordexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordSource.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.OnBoardSource) {
      com.biosimilarity.lift.model.seleKt.Absyn.OnBoardSource x = (com.biosimilarity.lift.model.seleKt.Absyn.OnBoardSource)o;
      return this.recordexpr_.equals(x.recordexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.recordexpr_.hashCode();
  }


}
