package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class PersistentSource extends RecordSource {
  public final StoreURL storeurl_;

  public PersistentSource(StoreURL p1) { storeurl_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordSource.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.PersistentSource) {
      com.biosimilarity.lift.model.seleKt.Absyn.PersistentSource x = (com.biosimilarity.lift.model.seleKt.Absyn.PersistentSource)o;
      return this.storeurl_.equals(x.storeurl_);
    }
    return false;
  }

  public int hashCode() {
    return this.storeurl_.hashCode();
  }


}
