package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ProbePossibility extends Modality {
  public final DomainCondition domaincondition_;

  public ProbePossibility(DomainCondition p1) { domaincondition_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.Modality.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ProbePossibility) {
      com.biosimilarity.lift.model.seleKt.Absyn.ProbePossibility x = (com.biosimilarity.lift.model.seleKt.Absyn.ProbePossibility)o;
      return this.domaincondition_.equals(x.domaincondition_);
    }
    return false;
  }

  public int hashCode() {
    return this.domaincondition_.hashCode();
  }


}
