package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class PushPrompt extends ContinueExpr {
  public final RLambdaExpr rlambdaexpr_1, rlambdaexpr_2;

  public PushPrompt(RLambdaExpr p1, RLambdaExpr p2) { rlambdaexpr_1 = p1; rlambdaexpr_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ContinueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.PushPrompt) {
      com.biosimilarity.lift.model.seleKt.Absyn.PushPrompt x = (com.biosimilarity.lift.model.seleKt.Absyn.PushPrompt)o;
      return this.rlambdaexpr_1.equals(x.rlambdaexpr_1) && this.rlambdaexpr_2.equals(x.rlambdaexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rlambdaexpr_1.hashCode())+this.rlambdaexpr_2.hashCode();
  }


}
