package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class PushPromptLCtxt extends ContinueLCtxt {
  public final RLambdaLCtxt rlambdalctxt_1, rlambdalctxt_2;

  public PushPromptLCtxt(RLambdaLCtxt p1, RLambdaLCtxt p2) { rlambdalctxt_1 = p1; rlambdalctxt_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ContinueLCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.PushPromptLCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.PushPromptLCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.PushPromptLCtxt)o;
      return this.rlambdalctxt_1.equals(x.rlambdalctxt_1) && this.rlambdalctxt_2.equals(x.rlambdalctxt_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rlambdalctxt_1.hashCode())+this.rlambdalctxt_2.hashCode();
  }


}
