package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class RecordSource implements java.io.Serializable {
  public abstract <R,A> R accept(RecordSource.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.OnBoardSource p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.PersistentSource p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.WireSource p, A arg);

  }

}
