package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class RecordPtn implements java.io.Serializable {
  public abstract <R,A> R accept(RecordPtn.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.RecordDestructor p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.RecordLiteral p, A arg);

  }

}
