package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class RecordVariable implements java.io.Serializable {
  public abstract <R,A> R accept(RecordVariable.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.RecordIdent p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.RecordWild p, A arg);

  }

}
