package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class RecordDestructor extends RecordPtn {
  public final ListDomainPtn listdomainptn_;
  public final RecordPtn recordptn_;

  public RecordDestructor(ListDomainPtn p1, RecordPtn p2) { listdomainptn_ = p1; recordptn_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordPtn.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.RecordDestructor) {
      com.biosimilarity.lift.model.seleKt.Absyn.RecordDestructor x = (com.biosimilarity.lift.model.seleKt.Absyn.RecordDestructor)o;
      return this.listdomainptn_.equals(x.listdomainptn_) && this.recordptn_.equals(x.recordptn_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listdomainptn_.hashCode())+this.recordptn_.hashCode();
  }


}
