package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class RecordExpr implements java.io.Serializable {
  public abstract <R,A> R accept(RecordExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Joined p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Isolated p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Consed p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Contexted p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Referenced p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Collected p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Emptied p, A arg);

  }

}
