package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class Referenced extends RecordExpr {
  public final RecordVariable recordvariable_;

  public Referenced(RecordVariable p1) { recordvariable_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.Referenced) {
      com.biosimilarity.lift.model.seleKt.Absyn.Referenced x = (com.biosimilarity.lift.model.seleKt.Absyn.Referenced)o;
      return this.recordvariable_.equals(x.recordvariable_);
    }
    return false;
  }

  public int hashCode() {
    return this.recordvariable_.hashCode();
  }


}
