package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class RLambdaPCtxt implements java.io.Serializable {
  public abstract <R,A> R accept(RLambdaPCtxt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ApplicationPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.AbstractionPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.KPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.GroundPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.MentionPCtxt p, A arg);

  }

}
