package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class RLambdaLCtxt implements java.io.Serializable {
  public abstract <R,A> R accept(RLambdaLCtxt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ApplicationLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.AbstractionLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.KLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.MentionLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.GroundLCtxt p, A arg);

  }

}
