package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class RLambdaExpr implements java.io.Serializable {
  public abstract <R,A> R accept(RLambdaExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Application p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Abstraction p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Continuation p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Mention p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.Value p, A arg);

  }

}
