package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class StructuralDomainCondition extends DomainCondition {
  public final RLambdaLCtxt rlambdalctxt_;

  public StructuralDomainCondition(RLambdaLCtxt p1) { rlambdalctxt_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.DomainCondition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.StructuralDomainCondition) {
      com.biosimilarity.lift.model.seleKt.Absyn.StructuralDomainCondition x = (com.biosimilarity.lift.model.seleKt.Absyn.StructuralDomainCondition)o;
      return this.rlambdalctxt_.equals(x.rlambdalctxt_);
    }
    return false;
  }

  public int hashCode() {
    return this.rlambdalctxt_.hashCode();
  }


}
