package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class SubcontPCtxt extends ContinuePCtxt {
  public final RLambdaPCtxt rlambdapctxt_1, rlambdapctxt_2;

  public SubcontPCtxt(RLambdaPCtxt p1, RLambdaPCtxt p2) { rlambdapctxt_1 = p1; rlambdapctxt_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ContinuePCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.SubcontPCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.SubcontPCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.SubcontPCtxt)o;
      return this.rlambdapctxt_1.equals(x.rlambdapctxt_1) && this.rlambdapctxt_2.equals(x.rlambdapctxt_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rlambdapctxt_1.hashCode())+this.rlambdapctxt_2.hashCode();
  }


}
