package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class URLRsrcLoc extends URLRsrcLocation {
  public final NetLocation netlocation_;

  public URLRsrcLoc(NetLocation p1) { netlocation_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.URLRsrcLocation.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.URLRsrcLoc) {
      com.biosimilarity.lift.model.seleKt.Absyn.URLRsrcLoc x = (com.biosimilarity.lift.model.seleKt.Absyn.URLRsrcLoc)o;
      return this.netlocation_.equals(x.netlocation_);
    }
    return false;
  }

  public int hashCode() {
    return this.netlocation_.hashCode();
  }


}
