package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class URLRsrcLocation implements java.io.Serializable {
  public abstract <R,A> R accept(URLRsrcLocation.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.URLRsrcPortLoc p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.URLRsrcLoc p, A arg);

  }

}
