package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValLPlaceHolder extends ValueLCtxtHole {
  public final LogicalGround logicalground_;

  public ValLPlaceHolder(LogicalGround p1) { logicalground_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueLCtxtHole.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValLPlaceHolder) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValLPlaceHolder x = (com.biosimilarity.lift.model.seleKt.Absyn.ValLPlaceHolder)o;
      return this.logicalground_.equals(x.logicalground_);
    }
    return false;
  }

  public int hashCode() {
    return this.logicalground_.hashCode();
  }


}
