package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValPPlaceHolder extends ValuePCtxtHole {
  public final String uident_;

  public ValPPlaceHolder(String p1) { uident_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValuePCtxtHole.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValPPlaceHolder) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValPPlaceHolder x = (com.biosimilarity.lift.model.seleKt.Absyn.ValPPlaceHolder)o;
      return this.uident_.equals(x.uident_);
    }
    return false;
  }

  public int hashCode() {
    return this.uident_.hashCode();
  }


}
