package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class ValuePCtxt implements java.io.Serializable {
  public abstract <R,A> R accept(ValuePCtxt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueAddPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueMultPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueNegPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueLitPCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueEmptyPCtxt p, A arg);

  }

}
