package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class ValueLCtxt implements java.io.Serializable {
  public abstract <R,A> R accept(ValueLCtxt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueAddLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueMultLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueNegLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueLitLCtxt p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueEmptyLCtxt p, A arg);

  }

}
