package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueLamLit extends ValueLiteral {
  public final RLambdaExpr rlambdaexpr_;

  public ValueLamLit(RLambdaExpr p1) { rlambdaexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueLiteral.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueLamLit) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueLamLit x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueLamLit)o;
      return this.rlambdaexpr_.equals(x.rlambdaexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.rlambdaexpr_.hashCode();
  }


}
