package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueAddExpr extends ValueExpr {
  public final ValueExpr valueexpr_1, valueexpr_2;

  public ValueAddExpr(ValueExpr p1, ValueExpr p2) { valueexpr_1 = p1; valueexpr_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueAddExpr) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueAddExpr x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueAddExpr)o;
      return this.valueexpr_1.equals(x.valueexpr_1) && this.valueexpr_2.equals(x.valueexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.valueexpr_1.hashCode())+this.valueexpr_2.hashCode();
  }


}
