package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueEmptyPCtxt extends ValuePCtxt {
  public final ValuePCtxtHole valuepctxthole_;

  public ValueEmptyPCtxt(ValuePCtxtHole p1) { valuepctxthole_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValuePCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueEmptyPCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueEmptyPCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueEmptyPCtxt)o;
      return this.valuepctxthole_.equals(x.valuepctxthole_);
    }
    return false;
  }

  public int hashCode() {
    return this.valuepctxthole_.hashCode();
  }


}
