package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueEmptyLCtxt extends ValueLCtxt {
  public final ValueLCtxtHole valuelctxthole_;

  public ValueEmptyLCtxt(ValueLCtxtHole p1) { valuelctxthole_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueLCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueEmptyLCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueEmptyLCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueEmptyLCtxt)o;
      return this.valuelctxthole_.equals(x.valuelctxthole_);
    }
    return false;
  }

  public int hashCode() {
    return this.valuelctxthole_.hashCode();
  }


}
