package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class Value extends RLambdaExpr {
  public final ValueExpr valueexpr_;

  public Value(ValueExpr p1) { valueexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RLambdaExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.Value) {
      com.biosimilarity.lift.model.seleKt.Absyn.Value x = (com.biosimilarity.lift.model.seleKt.Absyn.Value)o;
      return this.valueexpr_.equals(x.valueexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.valueexpr_.hashCode();
  }


}
