package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueAddLCtxt extends ValueLCtxt {
  public final ValueLCtxt valuelctxt_1, valuelctxt_2;

  public ValueAddLCtxt(ValueLCtxt p1, ValueLCtxt p2) { valuelctxt_1 = p1; valuelctxt_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueLCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueAddLCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueAddLCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueAddLCtxt)o;
      return this.valuelctxt_1.equals(x.valuelctxt_1) && this.valuelctxt_2.equals(x.valuelctxt_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.valuelctxt_1.hashCode())+this.valuelctxt_2.hashCode();
  }


}
