package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueAddPCtxt extends ValuePCtxt {
  public final ValuePCtxt valuepctxt_1, valuepctxt_2;

  public ValueAddPCtxt(ValuePCtxt p1, ValuePCtxt p2) { valuepctxt_1 = p1; valuepctxt_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValuePCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueAddPCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueAddPCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueAddPCtxt)o;
      return this.valuepctxt_1.equals(x.valuepctxt_1) && this.valuepctxt_2.equals(x.valuepctxt_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.valuepctxt_1.hashCode())+this.valuepctxt_2.hashCode();
  }


}
