package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public abstract class ValueExpr implements java.io.Serializable {
  public abstract <R,A> R accept(ValueExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueAddExpr p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueMultExpr p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueNegExpr p, A arg);
    public R visit(com.biosimilarity.lift.model.seleKt.Absyn.ValueLitExpr p, A arg);

  }

}
