package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueNegLCtxt extends ValueLCtxt {
  public final ValueLCtxt valuelctxt_;

  public ValueNegLCtxt(ValueLCtxt p1) { valuelctxt_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueLCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueNegLCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueNegLCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueNegLCtxt)o;
      return this.valuelctxt_.equals(x.valuelctxt_);
    }
    return false;
  }

  public int hashCode() {
    return this.valuelctxt_.hashCode();
  }


}
