package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueCharLit extends ValueLiteral {
  public final Character char_;

  public ValueCharLit(Character p1) { char_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueLiteral.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueCharLit) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueCharLit x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueCharLit)o;
      return this.char_.equals(x.char_);
    }
    return false;
  }

  public int hashCode() {
    return this.char_.hashCode();
  }


}
