package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueNegExpr extends ValueExpr {
  public final ValueExpr valueexpr_;

  public ValueNegExpr(ValueExpr p1) { valueexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueNegExpr) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueNegExpr x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueNegExpr)o;
      return this.valueexpr_.equals(x.valueexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.valueexpr_.hashCode();
  }


}
