package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValueLitLCtxt extends ValueLCtxt {
  public final ValueLiteral valueliteral_;

  public ValueLitLCtxt(ValueLiteral p1) { valueliteral_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValueLCtxt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValueLitLCtxt) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValueLitLCtxt x = (com.biosimilarity.lift.model.seleKt.Absyn.ValueLitLCtxt)o;
      return this.valueliteral_.equals(x.valueliteral_);
    }
    return false;
  }

  public int hashCode() {
    return this.valueliteral_.hashCode();
  }


}
