package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class ValWildCard extends ValuePCtxtHole {
  public final String wild_;

  public ValWildCard(String p1) { wild_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.ValuePCtxtHole.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.ValWildCard) {
      com.biosimilarity.lift.model.seleKt.Absyn.ValWildCard x = (com.biosimilarity.lift.model.seleKt.Absyn.ValWildCard)o;
      return this.wild_.equals(x.wild_);
    }
    return false;
  }

  public int hashCode() {
    return this.wild_.hashCode();
  }


}
