package com.biosimilarity.lift.model.seleKt.Absyn; // Java Package generated by the BNF Converter.

public class WireSource extends RecordSource {
  public final WireURL wireurl_;

  public WireSource(WireURL p1) { wireurl_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.seleKt.Absyn.RecordSource.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.seleKt.Absyn.WireSource) {
      com.biosimilarity.lift.model.seleKt.Absyn.WireSource x = (com.biosimilarity.lift.model.seleKt.Absyn.WireSource)o;
      return this.wireurl_.equals(x.wireurl_);
    }
    return false;
  }

  public int hashCode() {
    return this.wireurl_.hashCode();
  }


}
